name: Deploy Cormparse Backend
run-name: cormparse backend service ci-cd workflow
on:
  push:
    branches:
      - "master"
jobs:
  build_publish_docker_image:
    name: Test, Build And Publish cormparse backend service docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4.1.0
      # generate tags for the image
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            masterpiecekodz/cormparse-backend
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}},value=v1.0.0
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          push: false
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "masterpiecekodz/cormparse-backend:latest"
          format: "table"
          exit-code: "1"
          vuln-type: "os,library"
          severity: "CRITICAL"
          ignore-unfixed: true
      # I am pushhing manually bcos I want to be sure there is no vulnerability before pushing image.
      - run: docker push masterpiecekodz/cormparse-backend:1.0.0
      - run: docker push masterpiecekodz/cormparse-backend:latest
